apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: registry.mckinsey.com/dataops/cuda:v1.0.2
    name: cuda
    command: ["sh", "-c", "sleep 10000"]
    resources:
      limits:
        nvidia.com/gpu: "1"
