apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    govaultenv.io/container: alpine
    govaultenv.io/authpath: default@k8s/auth
spec:
  containers:
  - image: alpine:3.9.5
    name: alpine
    command: ["sh", "-c", "sleep 10000"]
