name: image
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jamhed/macgve
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update chart appVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.appVersion=env(GITHUB_REF_NAME)' charts/macgve/Chart.yaml
      - name: Bump chart version
        run: ./bump-chart.sh charts/macgve/Chart.yaml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
