name: image
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: publish
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: BUILTBY=${{github.actor}},VERSION=${{github.ref}},COMMIT=${{github.sha}},DATE=${{steps.date.outputs.date}}
          tags: ${GITHUB_REF_NAME}
      - name: Update chart appVersion
        uses: mikefarah/yq@master
        env:
          TAG: ${GITHUB_REF_NAME}
        with:
          cmd: yq -i '.appVersion=env(TAG)' charts/macgve/Chart.yaml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
